name: test_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #business logic
  flutter_bloc: ^8.0.1

  #db
  hive: ^2.1.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  path_provider: ^2.0.9

  #dart
  equatable: ^2.0.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true